### ISSUE TITLE
Fails on block assembly with R17.1R4

### ISSUE THREAD

**Issue by timjim333** [pointwise/VSP2CFD#1]
Hi, I'm trying to use this plugin but I get the following error below. Do I need to further setup pointwise to use this script? Many thanks.
```
Script: 
Script: Importing VspAircraft.stl...
Script: 
Script: 
Script: Generating farfield domain...
Script: 
Script: 
Script: Assembling unstructured block...
Script: 
Script: ----- TCL TRACE -----
Script: ERROR: invalid Glyph Object: ::pw::BlockUnstructured_1 ::pw::BlockUnstructured_2
Script: ERROR: usage (argument 2): pw::Application begin Solver entities
Script: ERROR: The given entities are not valid for this mode
Script:     while executing
Script: "pw::Application begin UnstructuredSolver [list $unsBlock]"
Script:     invoked from within
Script: "set solveMode [pw::Application begin UnstructuredSolver [list $unsBlock]] "
Script:     (file "/opt/pointwise/scripts/VSP2CFD/VSP2CFD.glf" line 103)
Script: ---------------------
Info: Script /opt/pointwise/scripts/VSP2CFD/VSP2CFD.glf failed.
```

**Comment by traviscarrigan** [comment]
The script seems to be failing when assembling the unstructured block. In fact, it looks like two blocks are created. The script looks for a single manifold STL and should only create a single block. If the STL is not manifold, or more than one block is created, it will fail. You can modify the script if you'd like to support more complex configurations.

**Comment by timjim333** [comment]
I see, it happened when I tried to use the default example in the repo actually! Could the different versions of Pointwise be behaving differently? 

I'll try and play with it and see if I can understand the scripting engine a little better.

**Comment by timjim333** [comment]
It seems that the send block is generated within the transport geometry? I have attached the resulting .pw file in the attachment. 
[output.pw.zip](https://github.com/pointwise/VSP2CFD/files/2448985/output.pw.zip)

**Comment by traviscarrigan** [comment]
You'll need to be running a later version of Pointwise. I just tested the example using Pointwise V18.2 and it worked perfectly.
